Problem 1

Generate a 2-dimensional NumPy array of shape (5, 4):

In [1]:
import numpy as np
import random
a = np.array([random.randint(1,50) for _ in range(20)])
b = a.reshape(5,4)

(a) Print the array and extract the elements along the anti-diagonal:

In [2]:
print(b)

[[23 12 44 29]
 [ 7 50 24 20]
 [13 37 39 36]
 [21 45  1 14]
 [42  3 33 49]]


In [3]:
row,col=0,3
while row<5 and col>=0:
    print(b[row][col])
    row+=1
    col-=1

29
24
37
21


(b) Compute and print the maximum value in each row of the array:

In [4]:
for row in range(5):
    print(np.max(b[row]))

44
50
39
45
49


(c) Create a new array containing only the elements less than or equal to the overall
mean of the array:

In [5]:
mean = np.mean(b)
c = np.array([])
for num in a:
    if num<mean:
        c = np.append(c, num)
print(c)

[23. 12.  7. 24. 20. 13. 21.  1. 14.  3.]


(d) Write a Python function numpy_boundary_traversal(matrix) that takes a NumPy
matrix and returns a list of elements visited along the boundary of the array in
clockwise order, starting from the top-left corner:

In [6]:
def numpy_boundary_traversal(matrix):
    res = []
    row,col = np.shape(matrix)
    # r,c=0,0
    res.extend(matrix[0, :col-1])
    res.extend(matrix[:row-1, -1])
    res.extend(matrix[-1, :0:-1])
    res.extend(matrix[:0:-1, 0])
    
    res = [int(x) for x in res]
    return res

In [7]:
numpy_boundary_traversal(b)

[23, 12, 44, 29, 20, 36, 14, 49, 33, 3, 42, 21, 13, 7]